version: "3"

services:
  zabbix_web:
    image: zabbix/zabbix-web-apache-mysql:alpine-4.2-latest
    hostname: zabbix_web
    ports:
      - "80:80"
    environment:
      - DB_SERVER_HOST=172.16.0.132
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix_server
      - PHP_TZ=America/Sao_Paulo
        #    links:
        #      - zabbix_server:zabbix_server

  zabbix_server:
    image: zabbix/zabbix-server-mysql:alpine-4.2-latest
    hostname: zabbix_server
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=172.16.0.132
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/app:/var/lib/grafana
      - ${PWD}/app:/var/log/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://172.16.0.132
      - GF_AUTH_LDAP_ENABLED=true
      - GF_AUTH_LDAP_CONFIG_FILE=/var/lib/grafana/ldap.toml
      - GF_AUTH_LDAP_ALLOW_SIGN_UP=true
      - GF_LOG_FILTERS=ldap:debug
      - GF_DATABASE_URL=mysql://grafana:grafana@172.16.0.132:3306/grafana
        #    links:
        #      - zabbix_web:zabbix_web
